name: Build and Upload Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UPDATE_CHANNEL: beta
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Using Node.js 18, can be changed if needed
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set permissions for Electron sandbox
        run: |
          sudo chown root node_modules/electron/dist/chrome-sandbox || true
          sudo chmod 4755 node_modules/electron/dist/chrome-sandbox || true

      - name: Run package:all script
        run: npm run package:all

      - name: Upload Linux build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifacts # You can customize this name
          path: release/build/ # Upload the entire contents of the release/build directory
